dota2_heroes_dict = {
    'abaddon': ['abaddon', 'абадон', 'абаддон'],
    'alchemist': ['alchemist', 'алхимист', 'алхимик'],
    'ancient-apparition': ['ancient-apparition', 'apparition', 'эншиент-аппаришн', 'апарат'],
    'anti-mage': ['anti-mage', 'am', 'анти-мейдж', 'антимаг', 'анти-маг', 'ам'],
    'arc-warden': ['arc-warden', 'arc', 'warden', 'арк-варден', 'арк', 'варден'],
    'axe': ['axe', 'акс'],
    'bane': ['bane', 'бейн'],
    'batrider': ['batrider', 'батрайдер'],
    'beastmaster': ['beastmaster', 'бистмастер'],
    'bloodseeker': ['bloodseeker', 'bs', 'бладсикер', 'бс'],
    'bounty-hunter': ['bounty-hunter', 'bh', 'баунти-хантер', 'бх'],
    'brewmaster': ['brewmaster', 'брюмастер'],
    'bristleback': ['bristleback', 'бристлбаек'],
    'broodmother': ['broodmother', 'brood', 'брудмазер', 'бруда'],
    'centaur-warrunner': ['centaur-warrunner', 'centaur', 'кентавр'],
    'chaos-knight': ['chaos-knight', 'ck', 'чаос-найт', 'чаос', 'цк'],
    'chen': ['chen', 'чен'],
    'clinkz': ['clinkz', 'клинкз', 'боник'],
    'clockwerk': ['clockwerk', 'клокверк', 'клок'],
    'crystal-maiden': ['crystal-maiden', 'cm', 'кристал-мейден', 'цм', 'цмка'],
    'dark-seer': ['dark-seer', 'ds', 'дарк-сир', 'дс'],
    'dark-willow': ['dark-willow', 'dw', 'дарк-виллоу', 'дв', 'виллоу', 'willow'],
    'dawnbreaker': ['dawnbreaker', 'db', 'даунбрейкер', 'дб'],
    'dazzle': ['dazzle', 'даззл'],
    'death-prophet': ['death-prophet', 'dp', 'дез-профет', 'дп', 'профет'],
    'disruptor': ['disruptor', 'дизраптор'],
    'doom': ['doom', 'дум'],
    'dragon-knight': ['dragon-knight', 'dk', 'драгон-найт', 'дк'],
    'drow-ranger': ['drow-ranger', 'drow', 'дроу-рейнджер', 'дроу', 'дровка'],
    'earth-spirit': ['earth-spirit', 'earth', 'эрт-спирит', 'ес', 'земеля', 'земля'],
    'earthshaker': ['earthshaker', 'эртшейкер', 'шейкер'],
    'elder-titan': ['elder-titan', 'elder', 'titan', 'элдер-титан', 'элдер', 'титан'],
    'ember-spirit': ['ember-spirit', 'ember', 'эмбер-спирит', 'эмбер'],
    'enchantress': ['enchantress', 'ench', 'энчантресс', 'энча'],
    'enigma': ['enigma', 'энигма'],
    'faceless-void': ['faceless-void', 'void', 'фейслесс-воид', 'фейслесс', 'воид'],
    'grimstroke': ['grimstroke', 'grim', 'гримстрок', 'грим'],
    'gyrocopter': ['gyrocopter', 'gyro', 'гайрокоптер', 'гиро'],
    'hoodwink': ['hoodwink', 'худвинк', 'белка'],
    'huskar': ['huskar', 'хускар'],
    'invoker': ['invoker', 'инвокер'],
    'io': ['io', 'висп'],
    'jakiro': ['jakiro', 'джакиро'],
    'juggernaut': ['juggernaut', 'jugger', 'джаггернаут', 'джагер', 'джага'],
    'keeper-of-the-light': ['keeper-of-the-light', 'kotl', 'кипер-оф-зе-лайт', 'кипер', 'котл'],
    'kunkka': ['kunkka', 'кунка'],
    'legion-commander': ['legion-commander', 'lc', 'легион-коммандер', 'легион', 'лц', 'лега'],
    'leshrac': ['leshrac', 'lesh', 'лешрак', 'леший'],
    'lich': ['lich', 'лич'],
    'lifestealer': ['lifestealer', 'ls', 'лайфстилер', 'найкс'],
    'lina': ['lina', 'лина'],
    'lion': ['lion', 'лион'],
    'lone-druid': ['lone-druid', 'ld', 'лон-друид', 'друид'],
    'luna': ['luna', 'луна'],
    'lycan': ['lycan', 'лайкан', 'ликан'],
    'magnus': ['magnus', 'магнус', 'кабанчик'],
    'marci': ['marci', 'марси'],
    'mars': ['mars', 'марс'],
    'medusa': ['medusa', 'медуза'],
    'meepo': ['meepo', 'мипо'],
    'mirana': ['mirana', 'мирана'],
    'monkey-king': ['monkey-king', 'mk', 'манки-кинг', 'мк', 'макака'],
    'morphling': ['morphling', 'morf', 'morph', 'морфлинг', 'морф'],
    'muerta': ['muerta', 'муэрта'],
    'naga-siren': ['naga-siren', 'naga', 'нага-сайрен', 'нага'],
    'natures-prophet': ['natures-prophet', 'нейчерс-профет', 'нейчерс', 'нп', 'фурион'],
    'necrophos': ['necrophos', 'necro', 'некрофос', 'некр'],
    'night-stalker': ['night-stalker', 'ns', 'найт-сталкер', 'balanar', 'сталкер', 'баланар'],
    'nyx-assassin': ['nyx-assassin', 'nyx', 'никс-ассассин', 'никс'],
    'ogre-magi': ['ogre-magi', 'ogre', 'огр-маг', 'огр'],
    'omniknight': ['omniknight', 'omnik', 'омникнайт', 'омник'],
    'oracle': ['oracle', 'оракл'],
    'outworld-destroyer': ['outworld-destroyer', 'od', 'аутворлд-дестройер', 'аутворлд', 'од'],
    'pangolier': ['pangolier', 'pango', 'панго', 'пангольер'],
    'phantom-assassin': ['phantom-assassin', 'pa', 'фантом-асассин', 'фантомка', 'па'],
    'phantom-lancer': ['phantom-lancer', 'pl', 'пл', 'фантом-лансер', 'лансер'],
    'phoenix': ['phoenix', 'феникс'],
    'primal-beast': ['primal-beast', 'pb', 'пб', 'праймал-бист', 'праймал', 'бист'],
    'puck': ['puck', 'пак', 'пук'],
    'pudge': ['pudge', 'падж', 'пудж', 'рудге'],
    'pugna': ['pugna', 'пугна'],
    'queen-of-pain': ['queen-of-pain', 'qop', 'квопа', 'квоп', 'квин', 'квин-оф-пейн'],
    'razor': ['razor', 'разор', 'рейзор'],
    'riki': ['riki', 'рики', 'рикимару'],
    'rubick': ['rubick', 'рубик'],
    'sand-king': ['sand-king', 'sk', 'санд', 'санд-кинг', 'ск'],
    'shadow-demon': ['shadow-demon', 'sd', 'сд', 'шадоу-демон', 'демон'],
    'shadow-fiend': ['shadow-fiend', 'sf', 'сф', 'шадоу-финд', 'финд'],
    'shadow-shaman': ['shadow-shaman', 'ss', 'шадоу-шаман', 'шаман'],
    'silencer': ['silencer', 'сайленсер', 'сало'],
    'skywrath-mage': ['skywrath-mage', 'sky', 'скай', 'скай-маг', 'скаймаг'],
    'slardar': ['slardar', 'слардар', 'селедка'],
    'slark': ['slark', 'сларк'],
    'snapfire': ['snapfire', 'снап', 'снапфаер'],
    'sniper': ['sniper', 'снайпер'],
    'spectre': ['spectre', 'спектр', 'спектра'],
    'spirit-breaker': ['spirit-breaker', 'sb', 'спирит-брейкер', 'баратрум', 'бара'],
    'storm-spirit': ['storm-spirit', 'storm', 'сторм-спирит', 'сторм', 'шторм', 'шторм-спирит'],
    'sven': ['sven', 'свен'],
    'techies': ['techies', 'течис', 'течка'],
    'templar-assassin': ['templar-assassin', 'ta', 'темплар-ассассин', 'темплар', 'темпларка'],
    'terrorblade': ['terrorblade', 'тб', 'террорблейд', 'террор', 'tb'],
    'tidehunter': ['tidehunter', 'tide', 'тайд', 'тайдхантер'],
    'timbersaw': ['timbersaw', 'тимбер', 'тимберсоу'],
    'tinker': ['tinker', 'тинкер'],
    'tiny': ['tiny', 'тини'],
    'treant-protector': ['treant-protector', 'treant', 'трент'],
    'troll-warlord': ['troll-warlord', 'troll', 'троль', 'тролль', 'тролл'],
    'tusk': ['tusk', 'таск'],
    'underlord': ['underlord', 'андер', 'андерлорд'],
    'undying': ['undying', 'андєд', 'андвинг'],
    'ursa': ['ursa', 'урса'],
    'vengeful-spirit': ['vengeful-spirit', 'vengeful', 'vs', 'венга'],
    'venomancer': ['venomancer', 'веном', 'веномансер', 'veno'],
    'viper': ['viper', 'вайпер'],
    'visage': ['visage', 'визаж'],
    'void-spirit': ['void-spirit', 'войд-спирит', 'вс', 'vs'],
    'warlock': ['warlock', 'варлок'],
    'weaver': ['weaver', 'вивер'],
    'windranger': ['windranger', 'виндрейнджер', 'wr', 'врка'],
    'winter-wyvern': ['winter-wyvern', 'wyvern', 'виверна'],
    'witch-doctor': ['witch-doctor', 'wd', 'вд', 'вич-доктор', 'вич', 'доктор', 'вдоктор', 'вичдоктор'],
    'wraith-king': ['wraith-king', 'wk', 'врєйс-кинг', 'папич', 'вк'],
    'zeus': ['zeus', 'зевс', 'зеус']
}

query_name = []

for values in dota2_heroes_dict.values():
    query_name.extend(values)
all_values = list(set(query_name))
