# Библиотека тут хранятся масивыб словари и тд

# Словарь всех имен героев по отношению к их сокращениям и тд
heroes_dict = {
    "abaddon": ["abaddon"],
    "alchemist": ["alchemist"],
    "ancient-apparition": ["ancient-apparition", "apparition", "aa", "ancient"],
    "anti-mage": ["anti-mage", "am"],
    "arc-warden": ["arc-warden", "arc", "warden"],
    "axe": ["axe"],
    "bane": ["bane"],
    "batrider": ["batrider"],
    "beastmaster": ["beastmaster"],
    "bloodseeker": ["bloodseeker", "bs"],
    "bounty-hunter": ["bounty-hunter", "bh"],
    "brewmaster": ["brewmaster"],
    "bristleback": ["bristleback"],
    "broodmother": ["broodmother", "brood"],
    "centaur-warrunner": ["centaur-warrunner", "centaur"],
    "chaos-knight": ["chaos-knight", "ck"],
    "chen": ["chen"],
    "clinkz": ["clinkz"],
    "clockwerk": ["clockwerk"],
    "crystal-maiden": ["crystal-maiden", "cm"],
    "dark-seer": ["dark-seer", "ds"],
    "dark-willow": ["dark-willow", "dw", "willow"],
    "dawnbreaker": ["dawnbreaker", "db"],
    "dazzle": ["dazzle"],
    "death-prophet": ["death-prophet", "dp"],
    "disruptor": ["disruptor"],
    "doom": ["doom"],
    "dragon-knight": ["dragon-knight", "dk"],
    "drow-ranger": ["drow-ranger", "drow"],
    "earth-spirit": ["earth-spirit", "earth"],
    "earthshaker": ["earthshaker"],
    "elder-titan": ["elder-titan", "elder", "titan"],
    "ember-spirit": ["ember-spirit", "ember"],
    "enchantress": ["enchantress", "ench"],
    "enigma": ["enigma"],
    "faceless-void": ["faceless-void", "void"],
    "grimstroke": ["grimstroke", "grim"],
    "gyrocopter": ["gyrocopter", "gyro"],
    "hoodwink": ["hoodwink"],
    "huskar": ["huskar"],
    "invoker": ["invoker"],
    "io": ["io"],
    "jakiro": ["jakiro"],
    "juggernaut": ["juggernaut", "jugger"],
    "keeper-of-the-light": ["keeper-of-the-light", "kotl"],
    "kunkka": ["kunkka"],
    "legion-commander": ["legion-commander", "lc"],
    "leshrac": ["leshrac", "lesh"],
    "lich": ["lich"],
    "lifestealer": ["lifestealer", "ls"],
    "lina": ["lina"],
    "lion": ["lion"],
    "lone-druid": ["lone-druid", "ld"],
    "luna": ["luna"],
    "lycan": ["lycan"],
    "magnus": ["magnus"],
    "marci": ["marci"],
    "mars": ["mars"],
    "medusa": ["medusa"],
    "meepo": ["meepo"],
    "mirana": ["mirana"],
    "monkey-king": ["monkey-king", "mk"],
    "morphling": ["morphling", "morf", "morph"],
    "muerta": ["muerta"],
    "naga-siren": ["naga-siren", "naga"],
    "natures-prophet": ["natures-prophet"],
    "necrophos": ["necrophos", "necro"],
    "night-stalker": ["night-stalker", "ns", "balanar"],
    "nyx-assassin": ["nyx-assassin", "nyx"],
    "ogre-magi": ["ogre-magi", "ogre"],
    "omniknight": ["omniknight", "omnik"],
    "oracle": ["oracle"],
    "outworld-destroyer": ["outworld-destroyer", "od"],
    "pangolier": ["pangolier", "pango"],
    "phantom-assassin": ["phantom-assassin", "pa"],
    "phantom-lancer": ["phantom-lancer", "pl"],
    "phoenix": ["phoenix"],
    "primal-beast": ["primal-beast", "pb"],
    'puck': ['puck'],
    'pudge': ['pudge'],
    'pugna': ['pugna'],
    'queen-of-pain': ['queen-of-pain', 'qop'],
    'razor': ['razor'],
    'riki': ['riki'],
    'rubick': ['rubick'],
    'sand-king': ['sand-king', 'sk'],
    'shadow-demon': ['shadow-demon', 'sd'],
    'shadow-fiend': ['shadow-fiend', 'sf'],
    'shadow-shaman': ['shadow-shaman', 'ss'],
    'silencer': ['silencer'],
    'skywrath-mage': ['skywrath-mage', 'sky'],
    'slardar': ['slardar'],
    'slark': ['slark'],
    'snapfire': ['snapfire'],
    'sniper': ['sniper'],
    'spectre': ['spectre'],
    'spirit-breaker': ['spirit-breaker', 'sb'],
    'storm-spirit': ['storm-spirit', 'storm'],
    'sven': ['sven'],
    'techies': ['techies'],
    'templar-assassin': ['templar-assassin', 'ta'],
    'terrorblade': ['terrorblade', 'tb'],
    'tidehunter': ['tidehunter', 'tide'],
    'timbersaw': ['timbersaw'],
    'tinker': ['tinker'],
    'tiny': ['tiny'],
    'treant-protector': ['treant-protector', 'treant'],
    'troll-warlord': ['troll-warlord', 'troll'],
    'tusk': ['tusk'],
    'underlord': ['underlord'],
    'undying': ['undying'],
    'ursa': ['ursa'],
    'vengeful-spirit': ['vengeful-spirit', 'vengeful', 'vs'],
    'venomancer': ['venomancer', 'veno'],
    'viper': ['viper'],
    'visage': ['visage'],
    'void-spirit': ['void-spirit', 'vs'],
    'warlock': ['warlock'],
    'weaver': ['weaver'],
    'windranger': ['windranger', 'wr'],
    'winter-wyvern': ['winter-wyvern', 'wyvern'],
    'witch-doctor': ['witch-doctor', 'wd'],
    'wraith-king': ['wraith-king', 'wk'],
    'zeus': ['zeus']

}

# МАсив всех имен героев
query_name = []
for values in heroes_dict.values():
    query_name.extend(values)
all_values = list(set(query_name))


# Словарь скинов для каждого героя и нфа про них
skins = {
    "abaddon": {
        "endless night": {
            "img": "img/hero/sets/abaddon/endless_night_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
        "Mace of the Chosen": {
            "img": "img/hero/sets/abaddon/mace_of_the_chosen_icon.png",
            "price": 120,
            "rarity": "rare",
            "availability": True,
            "type": "weapon"
        },
    },
    "alchemist": {
        "Lumpo and Rupertus": {
            "img": "img/hero/sets/alchemist/lumpo_and_rupertus_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
    },
    "ancient-apparition": {
        "Secrets of the Frost Singularity": {
            "img": "img/hero/sets/ancient-apparition/secrets_of_the_frost_singularity_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
    },
    "anti-mage": {
        "Brands if the Reaper": {
            "img": "img/hero/sets/anti-mage/brands_of_the_reaper_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
    },
    "arc-warden": {
        "Ire of the Ancient Gaoler": {
            "img": "img/hero/sets/arc-warden/ire_of_the_ancient_gaoler_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
    },
    "axe": [],
    "bane": [],
    "batrider": [],
    "beastmaster": [],
    "bloodseeker": [],
    "bounty-hunter": [],
    "brewmaster": [],
    "bristleback": [],
    "broodmother": [],
    "centaur-warrunner": [],
    "chaos-knight": [],
    "chen": [],
    "clinkz": [],
    "clockwerk": [],
    "crystal-maiden": [],
    "dark-seer": [],
    "dark-willow": [],
    "dawnbreaker": {
        "perception of the first light": {
            "img": "img/hero/sets/dawnbreaker/perception_of_the_first_light_icon.png",
            "price": 100,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
        "starlorn adjudication": {
            "img": "img/hero/sets/dawnbreaker/starlorn_adjudication_icon.png",
            "price": 120,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
        "dying light": {
            "img": "img/hero/sets/dawnbreaker/dying_light_icon.png",
            "price": 130,
            "rarity": "rare",
            "availability": True,
            "type": "set"
        },
        "astral herald": {
            "img": "img/hero/sets/dawnbreaker/astral_herald_icon.png",
            "price": 130,
            "rarity": "rare",
            "availability": False,
            "type": "set"
        }
    },
    "dazzle": [],
    "death-prophet": [],
    "disruptor": [],
    "doom": [],
    "dragon-knight": [],
    "drow-ranger": [],
    "earth-spirit": [],
    "earthshaker": [],
    "elder-titan": [],
    "ember-spirit": [],
    "enchantress": [],
    "enigma": [],
    "faceless-void": [],
    "grimstroke": [],
    "gyrocopter": [],
    "hoodwink": [],
    "huskar": [],
    "invoker": [],
    "io": [],
    "jakiro": [],
    "juggernaut": [],
    "keeper-of-the-light": [],
    "kunkka": [],
    "legion-commander": [],
    "leshrac": [],
    "lich": [],
    "lifestealer": [],
    "lina": [],
    "lion": [],
    "lone-druid": [],
    "luna": [],
    "lycan": [],
    "magnus": [],
    "marci": [],
    "mars": [],
    "medusa": [],
    "meepo": [],
    "mirana": [],
    "monkey-king": [],
    "morphling": [],
    "muerta": [],
    "naga-siren": [],
    "natures-prophet": [],
    "necrophos": [],
    "night-stalker": [],
    "nyx-assassin": [],
    "ogre-magi": [],
    "omniknight": [],
    "oracle": [],
    "outworld-destroyer": [],
    "pangolier": [],
    "phantom-assassin": [],
    "phantom-lancer": [],
    "phoenix": [],
    "primal-beast": [],
    "puck": [],
    "pudge": [],
    "pugna": [],
    "queen-of-pain": [],
    "razor": [],
    "riki": [],
    "rubick": [],
    "sand-king": [],
    "shadow-demon": [],
    "shadow-fiend": [],
    "shadow-shaman": [],
    "silencer": [],
    "skywrath-mage": [],
    "slardar": [],
    "slark": [],
    "snapfire": [],
    "sniper": [],
    "spectre": [],
    "spirit-breaker": [],
    "storm-spirit": [],
    "sven": [],
    "techies": [],
    "templar-assassin": [],
    "terrorblade": [],
    "tidehunter": [],
    "timbersaw": [],
    "tinker": [],
    "tiny": [],
    "treant-protector": [],
    "troll-warlord": [],
    "tusk": [],
    "underlord": [],
    "undying": [],
    "ursa": [],
    "vengeful-spirit": [],
    "venomancer": [],
    "viper": [],
    "visage": [],
    "void-spirit": [],
    "warlock": [],
    "weaver": [],
    "windranger": [],
    "winter-wyvern": [],
    "witch-doctor": [],
    "wraith-king": [],
    "zeus": []
}

